repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    hooks:
      - id: pre-commit-update
        args:
          - --verbose
    rev: v0.3.2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
    rev: v4.6.0
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
          - --fix
          - --exit-non-zero-on-fix
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        args:
          - --config=pyproject.toml
        types_or: [python, pyi, jupyter]
    rev: v0.4.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        args:
          - --config=pyproject.toml
        additional_dependencies:
          - types-pytz
    rev: v1.10.0
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          - --rcfile=pyproject.toml
          - --load-plugins=databricks.labs.pylint.all
      - id: pytest-unit-tests
        name: pytest-unit-tests
        entry: bash -c 'poetry run pytest -v tests --cov=src tests && poetry run coverage-badge -f -o assets/coverage.svg'
        language: system
        pass_filenames: false
        stages: [commit]
