repos:
  - hooks:
      - id: pre-commit-update
        args:
          - --verbose
    repo: https://gitlab.com/vojko.pribudic/pre-commit-update
    rev: v0.3.0
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
